spring:
  application:
    name: lagou-service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9998/lagou?characterEncoding=UTF-8
    username: root
    password: 123456
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 28080
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT
#lagou-cloud-email-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
lagou-service-code:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 60000
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 0
    MaxAutoRetriedNextServer: 0
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RoundRobinRule
logging:
  level:
    com.lagou.edu.service.ResumeServiceFeignClient: debug
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000